### ISSUE TITLE
add copy to clipboard support to the application

### ISSUE THREAD

**Issue by kjaymiller** [Aiven-Labs/aiven-cli-jq-cookbook#1]
Add a hyperlink to the markdown so that when the markdown is clicked, the entry is copied to the clipboard. 

#### What should happen

- The link is selected
- the system clipboard is updated with `Entry.command`
- a notification that the command was copied to the clipboard should appear temporarily

#### How do you test this

You could make a method that is called and test the method

**Comment by Tharun-DV** [comment]
`Not tested but this should work `
 
```py
import pyperclip
    
def action_copy(self):
        markdown_viewer = self.query_one("#markdown-viewer")
        selected_text = markdown_viewer.get_selected_text()
        if selected_text:
            pyperclip.copy(selected_text)
            self.push_message("Text copied to clipboard!")
        else:
            self.push_message("No text selected to copy!")
```

**Comment by kjaymiller** [comment]
@Tharun-DV  - did you want to contribute this to the project?

**Comment by Tharun-DV** [comment]
Yay but this is my first contribution

**Comment by kjaymiller** [comment]
@Tharun-DV  - happy to help you along the process.

If you don't mind please start with 

- fork the repo
- create a virtual environment
- install the dependencies

add the code into app.py and we'll create a new issue that integrates it into the project.
